services:
  app1:
    container_name: blockchain_1
    build: .
    volumes:
      - .:/app
    command: bash -c "python main.py --host 0.0.0.0 --port 5001"
    ports:
      - "5001:5001"
    environment:
      FLASK_APP: main.py
      FLASK_DEBUG: 1
 
  app2:
    container_name: blockchain_2
    build: .
    volumes:
      - .:/app
    command: bash -c "python main.py --host 0.0.0.0 --port 5002"
    ports:
      - "5002:5002"
    environment:
      FLASK_APP: main.py
      FLASK_DEBUG: 1
    depends_on:
      - app1
  
  app3:
    container_name: blockchain_3
    build: .
    volumes:
      - .:/app
    command: bash -c "python main.py --host 0.0.0.0 --port 5003"
    ports:
      - "5003:5003"
    environment:
      FLASK_APP: main.py
      FLASK_DEBUG: 1
    depends_on:
      - app2